// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wukodhrwligkihaucttm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1a29kaHJ3bGlna2loYXVjdHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2Nzk3ODksImV4cCI6MjA3NjI1NTc4OX0.Qk-rcG1_owrHzb8ebTLBwZ31Sz30D8hGpUEtcg6w9CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);